# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGIykwhseAqCiVVaoDhyih7AzQdLp_An
"""

import streamlit as st
import joblib
import numpy as np
import tldextract
import matplotlib.pyplot as plt
import time
import os

# ===============================
# Load Model
# ===============================
MODEL_PATH = os.path.join(os.path.dirname(__file__), "model.pkl")
model = joblib.load(MODEL_PATH)

# ===============================
# Session State Init
# ===============================
if "history" not in st.session_state:
    st.session_state.history = []

# ===============================
# Feature Extraction
# ===============================
def extract_features(url):
    ext = tldextract.extract(url)
    hostname = ext.domain + "." + ext.suffix if ext.suffix else ext.domain

    features = [
        len(url),
        len(hostname),
        int(any(c.isdigit() for c in hostname)),
        url.count("."),
        url.count("-"),
        url.count("@"),
        url.count("?"),
        url.count("&"),
        url.count("|"),
        int(ext.domain in url),
        1,
        365,
        1000,
        0,
        0
    ]
    return np.array(features).reshape(1, -1)

# ===============================
# UI
# ===============================
st.set_page_config(page_title="Phishing Detector", layout="wide")
st.title("🔒 Phishing Website Detection System")
st.markdown("### 🚀 AI-Powered Security Dashboard")

tab1, tab2, tab3 = st.tabs(["🔍 URL Checker", "📊 Dashboard", "⚙️ Manual Input"])

# ===============================
# TAB 1
# ===============================
with tab1:
    url_input = st.text_input("Enter Website URL:")

    if st.button("Analyze URL"):
        if url_input:

            with st.spinner("Analyzing..."):
                time.sleep(1)

                features = extract_features(url_input)

                prediction = model.predict(features)[0]

                # SAFE handling predict_proba
                try:
                    prob = model.predict_proba(features)[0][1]
                except:
                    prob = 0.0

                st.session_state.history.append((url_input, int(prediction), float(prob)))

                if prediction == 1:
                    st.error(f"⚠️ Phishing Website (Confidence: {prob:.2f})")
                else:
                    st.success(f"✅ Legitimate Website (Score: {prob:.2f})")

                st.download_button(
                    "📥 Download Result",
                    f"URL: {url_input}\nPrediction: {prediction}\nConfidence: {prob:.2f}",
                    file_name="result.txt"
                )

        else:
            st.warning("Please enter a URL")

    st.subheader("📜 History")
    st.write(st.session_state.history)

# ===============================
# TAB 2
# ===============================
with tab2:
    st.subheader("📊 Model Performance")

    models = ["Logistic Regression", "Random Forest", "SVM"]
    accuracy = [0.91, 0.96, 0.93]

    fig, ax = plt.subplots()
    ax.bar(models, accuracy)
    ax.set_ylabel("Accuracy")
    st.pyplot(fig)

    st.subheader("📈 Feature Importance")

    features = ["URL Length", "Hostname", "Digits", "Dots"]
    importance = [30, 25, 20, 25]

    fig2, ax2 = plt.subplots()
    ax2.pie(importance, labels=features, autopct='%1.1f%%')
    st.pyplot(fig2)

# ===============================
# TAB 3
# ===============================
with tab3:
    url_length = st.number_input("URL Length", 0, 500, 50)
    hostname_length = st.number_input("Hostname Length", 0, 100, 20)
    dots = st.number_input("Dots", 0, 20, 2)
    hyphens = st.number_input("Hyphens", 0, 20, 1)

    if st.button("Predict"):
        features = np.array([
            url_length,
            hostname_length,
            0,
            dots,
            hyphens,
            0, 0, 0, 0,
            1, 0, 1, 365, 1000, 0
        ]).reshape(1, -1)

        prediction = model.predict(features)[0]

        if prediction == 1:
            st.error("⚠️ Phishing Detected")
        else:
            st.success("✅ Legitimate Website")

# ===============================
# SIDEBAR
# ===============================
st.sidebar.title("Settings")

if st.sidebar.checkbox("Show Model Params"):
    st.sidebar.json(model.get_params())

st.sidebar.info("Final Year Project 🚀")